In [1]:
# Dependencies
import os
import sys
import collections
import pandas as pd
import urllib.request
import zipfile
from IPython.display import IFrame, HTML, FileLink

In [2]:
# Local
req_file = 'requirements.txt'

# Kaggle
if not os.path.exists(req_file):
    req_file = '/kaggle/input/osd-927/requirements.txt'

# Install dependencies
if os.path.exists(req_file):
    print(f"Installing {req_file} dependencies...")
    !{sys.executable} -m pip install -r {req_file} --quiet
else:
    print("No requirements.txt found. Skipping")

if os.path.exists('env.yml'):
    !mamba env update -n base -f env.yml || conda env update -n base -f env.yml
    print("Environment setup")
else:
    print("No mamba/conda dependencies needed")

Installing requirements.txt dependencies...
No mamba/conda dependencies needed

In [3]:
zip_path = "GLDS-755_scRNA_Seq_raw_multiqc_GLscRNAseq_report.zip"
url = f"http://nasa-osdr.s3.amazonaws.com/OSD-927/version-1/scRNA_Seq/{zip_path}"
extract_path = "./multiqc_osd-927"

# Download
print(f"Downloading from {url}...")
urllib.request.urlretrieve(url, zip_path)
print("Download complete")

# Extract
print("Extracting...")
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)
print("Extraction complete")

# Display
# HTML(filename='./multiqc_osd-927/raw_multiqc_GLscRNAseq_report/raw_multiqc_GLscRNAseq.html')
FileLink('./multiqc_osd-927/raw_multiqc_GLscRNAseq_report/raw_multiqc_GLscRNAseq.html')

Downloading from http://nasa-osdr.s3.amazonaws.com/OSD-927/version-1/scRNA_Seq/GLDS-755_scRNA_Seq_raw_multiqc_GLscRNAseq_report.zip...
Download complete
Extracting...
Extraction complete

/mnt/c/Users/nicks/Bioinformatics/NASA/Nasa_vault/in_progress/OSD-927/multiqc_osd-927/raw_multiqc_GLscRNAseq_report/raw_multiqc_GLscRNAseq.html

In [4]:
# Selected sample id
sample_id = "SRX28491903" 

# fastq urls
base_url = "http://nasa-osdr.s3.amazonaws.com/OSD-927/version-1/scRNA-Seq/"
r1_url = f"{base_url}GLDS-755_scRNA-Seq_{sample_id}_R1_raw.fastq.gz"
r2_url = f"{base_url}GLDS-755_scRNA-Seq_{sample_id}_R2_raw.fastq.gz"

# Subsample
print(f"Subsampling {sample_id}...")
!curl {r1_url} | gunzip -c | head -n 400000 > r1_sub.fastq
!curl {r2_url} | gunzip -c | head -n 400000 > r2_sub.fastq
print("Subsampling complete.")

# View first sequence
!head -n 4 r1_sub.fastq

Subsampling SRX28491903...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 2932M    0 90216    0     0   157k      0  5:18:10 --:--:--  5:18:10  157k
gzip: stdout: Broken pipe
  0 2932M    0 2324k    0     0  1542k      0  0:32:26  0:00:01  0:32:25 1544k
curl: (23) Failure writing output to destination
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 6428M    0 2974k    0     0  1617k      0  1:07:49  0:00:01  1:07:48 1617k
gzip: stdout: Broken pipe
  0 6428M    0 4666k    0     0  2026k      0  0:54:08  0:00:02  0:54:06 2026k
curl: (23) Failure writing output to destination
Subsampling complete.
@SRR33245654.1 A00111:540:HGVN3DSXY:1:1101:4200:1000 1
TACACCCTCCTGTTATCTATGTTCTGGC
+
FFF,FFFFFF:FFFFFFFFFFFFFFFFF

In [5]:
# Download metadata
!curl -O http://nasa-osdr.s3.amazonaws.com/OSD-927/version-1/metadata/OSD-927_metadata_OSD-927-ISA.zip

# Unzip metadata
!unzip -o OSD-927_metadata_OSD-927-ISA.zip -d metadata/

# Read available files
df_study = pd.read_csv('metadata/s_OSD-927.txt', sep='\t')
df_assay = pd.read_csv('metadata/a_OSD-927_transcription-profiling_single-cell-rna-sequencing_Illumina.txt', sep='\t')
df_investigation = pd.read_csv('metadata/i_Investigation.txt', sep='\t')

display(df_study.head())
display(df_assay.head())
display(df_investigation.head())

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 27849  100 27849    0     0  59514      0 --:--:-- --:--:-- --:--:-- 59506
Archive:  OSD-927_metadata_OSD-927-ISA.zip
 extracting: metadata/s_OSD-927.txt
 extracting: metadata/i_Investigation.txt
 extracting: metadata/a_OSD-927_transcription-profiling_single-cell-rna-sequencing_Illumina.txt

,Source Name,Sample Name,Characteristics[Organism],Term Source REF,Term Accession Number,Characteristics[Strain],Term Source REF.1,Term Accession Number.1,Characteristics[Genotype],Term Source REF.2,...,Parameter Value[Euthanasia Location],Parameter Value[Dissection Condition],Parameter Value[Euthanasia Method],Parameter Value[Sample Preservation Method],Term Source REF.8,Term Accession Number.8,Parameter Value[Time between landing to euthanasia],Unit.2,Term Source REF.9,Term Accession Number.9
0,HC_LAR_19,GSM8947894,Mus musculus,NCBITAXON,http://purl.bioontology.org/ontology/NCBITAXON...,BALB/cAnNTac,OSD,https://osdr.nasa.gov/,Wild Type,NCIT,...,On Earth,Upon euthanasia,"Bilateral thoracotomy with sedation, Cardiac p...",fresh specimen,OBI,http://purl.obolibrary.org/obo/OBI_0000971,2 - 4,day,UO,http://purl.obolibrary.org/obo/UO_0000033
1,HC_LAR_10,GSM8947895,Mus musculus,NCBITAXON,http://purl.bioontology.org/ontology/NCBITAXON...,BALB/cAnNTac,OSD,https://osdr.nasa.gov/,Wild Type,NCIT,...,On Earth,Upon euthanasia,"Bilateral thoracotomy with sedation, Cardiac p...",fresh specimen,OBI,http://purl.obolibrary.org/obo/OBI_0000971,2 - 4,day,UO,http://purl.obolibrary.org/obo/UO_0000033
2,HC_LAR_20,GSM8947896,Mus musculus,NCBITAXON,http://purl.bioontology.org/ontology/NCBITAXON...,BALB/cAnNTac,OSD,https://osdr.nasa.gov/,Wild Type,NCIT,...,On Earth,Upon euthanasia,"Bilateral thoracotomy with sedation, Cardiac p...",fresh specimen,OBI,http://purl.obolibrary.org/obo/OBI_0000971,2 - 4,day,UO,http://purl.obolibrary.org/obo/UO_0000033
3,FL_LAR_09,GSM8947897,Mus musculus,NCBITAXON,http://purl.bioontology.org/ontology/NCBITAXON...,BALB/cAnNTac,OSD,https://osdr.nasa.gov/,Wild Type,NCIT,...,On Earth,Upon euthanasia,"Bilateral thoracotomy with sedation, Cardiac p...",fresh specimen,OBI,http://purl.obolibrary.org/obo/OBI_0000971,2 - 4,day,UO,http://purl.obolibrary.org/obo/UO_0000033
4,FL_LAR_19,GSM8947898,Mus musculus,NCBITAXON,http://purl.bioontology.org/ontology/NCBITAXON...,BALB/cAnNTac,OSD,https://osdr.nasa.gov/,Wild Type,NCIT,...,On Earth,Upon euthanasia,"Bilateral thoracotomy with sedation, Cardiac p...",fresh specimen,OBI,http://purl.obolibrary.org/obo/OBI_0000971,2 - 4,day,UO,http://purl.obolibrary.org/obo/UO_0000033

,Sample Name,Protocol REF,Extract Name,Protocol REF.1,Parameter Value[Cell Count],Parameter Value[Library Kit],Parameter Value[Library Selection],Parameter Value[Library Layout],Parameter Value[Stranded],Protocol REF.2,...,Protocol REF.3,Parameter Value[Read Depth],Unit.2,Term Source REF.2,Term Accession Number.2,Parameter Value[rRNA Contamination],Unit.3,Term Source REF.3,Term Accession Number.3,Parameter Value[MultiQC File Names]
0,GSM8947894,Cell Isolation,GSM8947894,Library Construction,5000,GemCode Single-Cell 3’ Gel Bead and Library v3...,polyA enrichment,PAIRED,UNSTRANDED,Nucleic Acid Sequencing,...,GeneLab raw data processing protocol,419834860,read,SO,http://purl.obolibrary.org/obo/SO_0000150,5.13,percent,UO,http://purl.obolibrary.org/obo/UO_0000187,GLDS-755_scRNA_Seq_raw_multiqc_GLscRNAseq_repo...
1,GSM8947895,Cell Isolation,GSM8947895,Library Construction,5000,GemCode Single-Cell 3’ Gel Bead and Library v3...,polyA enrichment,PAIRED,UNSTRANDED,Nucleic Acid Sequencing,...,GeneLab raw data processing protocol,146660371,read,SO,http://purl.obolibrary.org/obo/SO_0000150,5.66,percent,UO,http://purl.obolibrary.org/obo/UO_0000187,GLDS-755_scRNA_Seq_raw_multiqc_GLscRNAseq_repo...
2,GSM8947896,Cell Isolation,GSM8947896,Library Construction,5000,GemCode Single-Cell 3’ Gel Bead and Library v3...,polyA enrichment,PAIRED,UNSTRANDED,Nucleic Acid Sequencing,...,GeneLab raw data processing protocol,192348320,read,SO,http://purl.obolibrary.org/obo/SO_0000150,4.90,percent,UO,http://purl.obolibrary.org/obo/UO_0000187,GLDS-755_scRNA_Seq_raw_multiqc_GLscRNAseq_repo...
3,GSM8947897,Cell Isolation,GSM8947897,Library Construction,5000,GemCode Single-Cell 3’ Gel Bead and Library v3...,polyA enrichment,PAIRED,UNSTRANDED,Nucleic Acid Sequencing,...,GeneLab raw data processing protocol,248818215,read,SO,http://purl.obolibrary.org/obo/SO_0000150,5.72,percent,UO,http://purl.obolibrary.org/obo/UO_0000187,GLDS-755_scRNA_Seq_raw_multiqc_GLscRNAseq_repo...
4,GSM8947898,Cell Isolation,GSM8947898,Library Construction,5000,GemCode Single-Cell 3’ Gel Bead and Library v3...,polyA enrichment,PAIRED,UNSTRANDED,Nucleic Acid Sequencing,...,GeneLab raw data processing protocol,231034353,read,SO,http://purl.obolibrary.org/obo/SO_0000150,4.87,percent,UO,http://purl.obolibrary.org/obo/UO_0000187,GLDS-755_scRNA_Seq_raw_multiqc_GLscRNAseq_repo...

                                                                                                                                                                                           ONTOLOGY SOURCE REFERENCE
Term Source Name        EFO                                        NCIT NaN                                     OBI                                        CRO MESH OSD                                          RBO
Term Source File        http://data.bioontology.org/ontologies/EFO NaN  http://purl.obolibrary.org/obo/ncit.owl http://data.bioontology.org/ontologies/OBI NaN NaN  https://osdr.nasa.gov/                       NaN
Term Source Version     132                                        NaN  18.10e                                  29                                         NaN NaN  1.0                                          NaN
Term Source Description Experimental Factor Ontology               NaN  NCI Thesaurus OBO Edition               Ontology for Biomedical Investigations     NaN NaN  User defined terms                           NaN
INVESTIGATION           NaN                                        NaN  NaN                                     NaN                                        NaN NaN  NaN                                          NaN

#### Method validation
- GemCode Single-Cell 3’ Gel Bead and Library v3
- Read 1 structure: 28bp total
- Barcode length: 16bp
- UMI length: 12bp

In [6]:
# 10x v3 = 16bp Barcode, 12bp UMI
# 10x v2 = 16bp Barcode, 10bp UMI
bc_len = 16
umi_len = 12

In [7]:
## Validate scRNA-Seq subsample 1
# Dictionaries
cell_umis = collections.defaultdict(set)
read_counts = collections.defaultdict(int)

with open('r1_sub.fastq', 'r') as f:
    for i, line in enumerate(f):
        if i % 4 == 1:
            barcode = line[:16]
            umi = line[16:28]
            cell_umis[barcode].add(umi)
            read_counts[barcode] += 1

# Saturation (unique reads)
top_cell = max(read_counts, key=read_counts.get)
unique_mols = len(cell_umis[top_cell])
total_reads = read_counts[top_cell]

saturation = 1 - (unique_mols / total_reads)
print(f"Top Cell ({top_cell}) Analysis:")
print(f"- Reads: {total_reads}")
print(f"- Unique Molecules (UMIs): {unique_mols}")
print(f"- Saturation: {saturation:.2%}")

Top Cell (TGCAGTATCTTGATTC) Analysis:
- Reads: 85
- Unique Molecules (UMIs): 78
- Saturation: 8.24%

In [8]:
## Validate scRNA-Seq subsample 2 
# Count sequences
r2_counts = collections.Counter()
with open('r2_sub.fastq', 'r') as f:
    for i, line in enumerate(f):
        if i % 4 == 1:
            r2_counts[line.strip()] += 1

print("Top 5 overrepresented sequences:")
for seq, count in r2_counts.most_common(5):
    percentage = (count / 100000) * 100
    print(f"    [{count} reads | {percentage:.2f}%]: {seq}")

Top 5 overrepresented sequences:
    [107 reads | 0.11%]: AAGCAGTGGTATCAACGCAGAGTACATGGGGAGGCATTCAGGCAGCGAGAGCAGAGCAGCGTAGAGCAGCACAGCTGAGCTCGTGAGGCAG
    [105 reads | 0.10%]: GTTTCATCTCGCAGAAGGGTGCTCCGGCTCTGGAGGGCACCGCCAGTGTGTTTGCACCAGGAGACAGTAAAGGAGCTGCTGCAGGCAGGTT
    [66 reads | 0.07%]: GCTCCTTCCCTATAGTGTTTCATCTCGCAGAAGGGTGCTCCGGCTCTGGAGGGCACCGCCAGTGTGTTTGCACCAGGAGACAGTAAAGGAG
    [65 reads | 0.07%]: CTCGCAGAAGGGTGCTCCGGCTCTGGAGGGCACCGCCAGTGTGTTTGCACCAGGAGACAGTAAAGGAGCTGCTGCAGGCAGGTTCTGCACA
    [65 reads | 0.07%]: CTCCTTCCCTATAGTGTTTCATCTCGCAGAAGGGTGCTCCGGCTCTGGAGGGCACCGCCAGTGTGTTTGCACCAGGAGACAGTAAAGGAGC

Top sequence is normal TSO (Template Switching Oligo) for library prep method